version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "8080:8080"
      - "3000:3000" # optional: API and health on 3000 inside container
    volumes:
      # Mount the database file so it persists and can be accessed from host
      - ./jobs.db:/app/jobs.db
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 